Repository Project-Glint/glint-front, pull requests merged in 2024-11, with the labels that each got.

#21 Create glint-ci.yml
  .github/workflows/glint-ci.yml
Labels: FEAT

#22 Feat/#20 GitHub actions setting
  .github/workflows/glint-ci.yml
  src/assets/index.ts
Labels: FEAT

#26 feat: deploy node, pnpm version 명시적 지정으로 수정 (#25)
  .github/workflows/glint-ci.yml
Labels: FEAT

#31 feat: git clone 명령어 추가 (#30)
  .github/workflows/glint-ci.yml
Labels: FEAT

#32 feat: git clone 명령어 추가 (#30) (#31)
  .github/workflows/glint-ci.yml
Labels: MERGE

#33 Feat/#30 git clone 수정
  .github/workflows/glint-ci.yml
Labels: FEAT

#34 Feat/#30 git clone 수정 (#33)
  .github/workflows/glint-ci.yml
Labels: MERGE

#35 Feat/#30 git clone 수정
  .github/workflows/glint-ci.yml
Labels: FEAT

#38 Feat/#32 api 세팅
  package.json
  pnpm-lock.yaml
  src/api/axios.ts
  src/api/register.ts
  src/app/page.tsx
  src/hooks/queries/register.ts
  src/types/api/register.ts
Labels: FEAT

#39 Style/#36 디자인토큰 적용
  .storybook/preview.ts
  .storybook/preview.tsx
  src/app/ClientProviders.tsx
  src/app/layout.tsx
  src/assets/fonts/GeistMonoVF.woff
  src/assets/fonts/GeistVF.woff
  src/assets/fonts/PretendardVariable.woff2
  src/components/button/Button.styled.ts
  src/components/imageUpload/ImageUpload.styled.ts
  src/components/input/Input.styled.ts
  src/styles/globalStyle.ts
  src/styles/index.ts
  src/styles/themes/colors.ts
  src/styles/themes/fonts.ts
  src/styles/themes/index.ts
  src/styles/themes/shadows.ts
  src/styles/themes/theme.ts
  src/types/declare/emotions.d.ts
  stories/Colors.stories.tsx
  stories/Typography.stories.tsx
Labels: FEAT, STYLE

#44 feat: #41 카카오 로그인 기능 구현 및 token 세팅 작업
  src/api/register.ts
  src/app/login/action.ts
  src/app/login/callback/page.tsx
  src/app/login/login.styled.ts
  src/app/login/page.tsx
  src/app/page.tsx
  src/types/api/signup.ts
Labels: FEAT

#47 feat: 공통 input 기능 추가
  src/api/register.ts
  src/app/login/callback/page.tsx
  src/app/signup/containers/index.ts
  src/app/signup/containers/signupAuth/SignupAuth.tsx
  src/app/signup/containers/signupBirth/SignupBirth.styled.ts
  src/app/signup/containers/signupBirth/SignupBirth.tsx
  src/app/signup/containers/signupBirth/index.ts
  src/app/signup/containers/signupCharacter/SignupCharacter.tsx
  src/app/signup/containers/signupGender/SignupGender.tsx
  src/app/signup/containers/signupJob/SignupJob.tsx
  src/app/signup/containers/signupNicknameHeight/SignupNicknameHeight.tsx
  src/app/signup/page.tsx
  src/assets/icons/ic_xcircle.svg
  src/assets/icons/index.ts
  src/assets/statics/signup.tsx
  src/components/controller/TextController.tsx
  src/components/input/Input.styled.ts
  src/components/input/Input.tsx
  src/components/layout/footer/signup/SignupFooter.styled.ts
  src/hooks/queries/register.ts
  src/styles/globalStyle.ts
  src/types/api/signup.ts
  src/types/domain/signup/signup.ts
Labels: FEAT

#49 Feat/#46 회원가입 추가개발
  src/app/signup/containers/index.ts
  src/app/signup/containers/signupKeyword/SignupKeywork.styled.ts
  src/app/signup/containers/signupKeyword/SignupKeywork.tsx
  src/app/signup/containers/signupKeyword/index.ts
  src/app/signup/containers/signupSelfIntroduce/SignupSelfIntroduce.styled.ts
  src/app/signup/containers/signupSelfIntroduce/SignupSelfIntroduce.tsx
  src/app/signup/containers/signupSelfIntroduce/index.ts
  src/app/signup/page.tsx
  src/assets/icons/ic_x.svg
  src/assets/icons/index.ts
  src/assets/statics/signup.tsx
  src/components/badge/Badge.styled.ts
  src/components/badge/Badge.tsx
  src/components/controller/TextareaController.tsx
  src/components/input/Input.styled.ts
  src/components/input/textarea/Textarea.styled.ts
  src/components/input/textarea/Textarea.tsx
  src/types/domain/signup/signup.ts
Labels: FEAT

#50 Feat/#48 지역,프로필 스크린제작
  package.json
  pnpm-lock.yaml
  src/api/region.ts
  src/api/signup.ts
  src/app/login/callback/page.tsx
  src/app/page.tsx
  src/app/signup/containers/index.ts
  src/app/signup/containers/signupGender/SignupGender.tsx
  src/app/signup/containers/signupKeyword/SignupKeywork.tsx
  src/app/signup/containers/signupProfile/SignupProfile.styled.ts
  src/app/signup/containers/signupProfile/SignupProfile.tsx
  src/app/signup/containers/signupProfile/index.ts
  src/app/signup/containers/signupRegion/SignupRegion.styled.ts
  src/app/signup/containers/signupRegion/SignupRegion.tsx
  src/app/signup/containers/signupRegion/index.ts
  src/app/signup/page.tsx
  src/assets/icons/ic_blackX.svg
  src/assets/icons/ic_handlebar.svg
  src/assets/icons/ic_plus.svg
  src/assets/icons/ic_whiteX.svg
  src/assets/icons/index.ts
  src/components/button/Button.tsx
  src/components/imageUpload/ImageUpload.styled.ts
  src/components/imageUpload/ImageUpload.tsx
  src/components/index.ts
  src/components/input/Input.styled.ts
  src/components/modal/baseModal/BottomBaseModal.styled.ts
  src/components/modal/baseModal/BottomBaseModal.tsx
  src/components/modal/baseModal/index.ts
  src/components/modal/index.ts
  src/components/modal/regionModal/RegionModal.styled.ts
  src/components/modal/regionModal/RegionModal.tsx
  src/components/modal/regionModal/index.ts
  src/hooks/index.ts
  src/hooks/queries/index.ts
  src/hooks/queries/region.ts
  src/hooks/queries/signup.ts
  src/types/api/index.ts
  src/types/api/region.ts
  src/types/domain/signup/signup.ts
  src/types/index.ts
Labels: FEAT
